### PR TITLE
Add archive page & other perks

### PR DESCRIPTION
**Pull request by cy-by**
# Summary
Hello @Vwampage & @beckyrother 👋 
I've create a new page and added some bells and whistles ✨

# Main Feature
The main addition is a new archive page. I took information for previous git commits and issues submitted by @brianmontanaweb. Not everyone has slides, but they can be added in the future.

## Link on home page
I don't know y'all want the link to the archive page from the home page, so I added it toward the end of the page:
home-link-to-archive

## Preview of archive page
More links to slides to come in the future. I tried to use the existing design patterns as much as possible. Here's a preview of the entire archive page:
new-archive-page

----
# Some additional perks
## Editor Config
I added an `.editorconfig` file so that anyone who develops the website will have consistent spacing and line returns. For example, before the `index.html` used tabs while `style.css` used spaces. Now all files should be consistent and future files will stay in line. More information about editorconfig can be found on [their website](http://editorconfig.org/).

## Dynamic Footer Year
I added a small bit of JavaScript to keep the year in the footer current. We'll never have to worry about updating it.
footer-dynamic-year

## More Meta Tags
I used the site [heymeta.com](https://www.heymeta.com/) to generate all the meta tags appropriate for the different social sites. So that when people share the url, there will be a nice preview (will probably show up in Slack too!)
sharing-social-card-preview

## Added `<html>`
I noticed there wasn't an actual `<html></html>` tag. This is ok since the browser automatically adds it. But I added it just to be clear. I also added the `lang` attribute to be clear what language the site is in.

## Simple Readme
I added a small readme just have have showing on the github page. Nothing fancy here.

### CODE REVIEW

**Comment by tomsapps** [comment]
Nice job @coltborg!

A few questions:
- If we plan to continue adding talks, do you think it'd be worth writing a script that generates the /archive page from a .json file or something? 
- The favicon is not showing up on either of the pages on my machine and I can't find a reference to the .ico in any of the files in either repo, I might be missing something but I'm not sure how it's showing up in prod.
- Should we make the spacing around the line break between the "Talk Archive" header and list of talks even?
- nit ~ I think there's an extra comma after David's name :P

**Comment by beckyrother** [comment]
I AM SO EXCITED TO SEE THIS!!! @coltborg!!!! 

@tomsapps agree the spacing is a bit awkward between the header, subhead, and list of talks. Rather than adjusting the spacing, though, since it's following the style from the home page, can the subhead just get longer? 

- Clicking on the icon in the top should take the user back to the home page; can the buttons at the top stay the same between each page?
- Add a `home` button under the subhead
- Subhead copy to come :)

**Comment by tomsapps** [comment]
@beckyrother making the subhead longer is a good idea! I've never thought of that; My mind is actually blown lol

**Review by brianmontanaweb — APPROVED** [review]
Looking good, let's put an open issue for building this as a Jekyll site so we can just update a JSON file for stuff like the archive and current speaker and for future us to manage it better.

**Comment by tomsapps** [comment]
@brianmontanaweb Taking a look at Jekyll for the first time and I'm wondering if we really need it right now? I was thinking we could write a loop that would parse a config file containing objects with `title`, `subtitle`, `body` & `slides` fields and generates the `archive.html` file that Colt added. Kinda suggesting to reinvent the wheel here but I think we could pull it off with a few lines of js. Thoughts?

**Comment by Vwampage** [comment]
@brianmontanaweb @tomsapps @coltborg is the work done here sufficient to merge or is there yet more to do before it's ready for primetime?

**Comment by brianmontanaweb** [comment]
I'll verify the PR over lunch and test locally first

On Apr 16, 2018 11:21 PM, Vwampage <notifications@github.com> wrote:

@brianmontanaweb<https://github.com/brianmontanaweb> @tomsapps<https://github.com/tomsapps> @coltborg<https://github.com/coltborg> is the work done here sufficient to merge or is there yet more to do before it's ready for primetime?

**Comment by brianmontanaweb** [comment]
All good, verified it works and looks good locally 👍

**Comment by Vwampage** [comment]
O SHIT HERE COME DAT MERGE.

**Pull request merged**
